services:
  redis:
    image: 'redis'
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 10s
      retries: 5
    tty: true
  
  api:
    build:
      context: ./deploy/images/api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '8080:8080'
    environment:
      AUTH_SERVICE_HOST: auth-grpc
    depends_on:
      - auth-grpc
    tty: true

  auth-grpc:
    build: 
      context: ..
      dockerfile: deploy/images/auth/Dockerfile
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
    container_name: auth-grpc
    restart: always
    depends_on:
      - redis
    ports:
      - '5001:5001'
    tty: true

  postgres:
    build:
      context: ./deploy/images/postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './_postgres:/docker-entrypoint-initdb.d'
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    tty: true

  user-grpc:
    build: 
      context: ..
      dockerfile: deploy/images/user/Dockerfile
    container_name: user-grpc
    restart: always
    depends_on:
      - postgres
    ports:
      - '5002:5002'
    tty: true
