apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: online-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-config
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-config
        configMap:
          name: postgres-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: online-store
data:
  postgresql.conf: |
    max_connections = 40
    listen_addresses = '*'
    shared_preload_libraries = 'pg_stat_statements,auto_explain'
    statement_timeout = 3000
    lock_timeout = 1000
    logging_collector = on
    log_min_duration_statement = 1000
    log_duration = on
    log_statement = 'all'
    log_lock_waits = on
    log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a,client=%h '
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_temp_files = 1024
    log_error_verbosity = default
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
    pg_stat_statements.track_utility = off
    pg_stat_statements.save = on
    auto_explain.log_min_duration = '1s'
    auto_explain.log_analyze = true
    auto_explain.log_buffers = true
    auto_explain.log_verbose = off
    auto_explain.log_format = 'text'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: online-store
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432